package com.recoverpro.server.entity;

import io.hypersistence.utils.hibernate.type.json.JsonType;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.Type;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.List;
import java.util.UUID;

/**
 * Optimised daily route per agent.
 *
 * Per-agent-per-day record with the ordered assignment list and the
 * optimisation score. Generated by {@code AllocationOptimizerServiceImpl}
 * on each optimize() call; the mobile app fetches this row instead of
 * re-running the optimizer per assignment.
 */
@Entity
@Table(name = "route_plans", indexes = {
        @Index(name = "idx_route_plans_agent_date", columnList = "agent_id, plan_date", unique = true),
        @Index(name = "idx_route_plans_org",        columnList = "organization_id")
})
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class RoutePlan {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    @Column(name = "agent_id", nullable = false)
    private UUID agentId;

    @Column(name = "organization_id", nullable = false)
    private UUID organizationId;

    @Column(name = "plan_date", nullable = false)
    private LocalDate planDate;

    /** Ordered assignment ids in execution order -- the mobile app's visit queue. */
    @Type(JsonType.class)
    @Column(name = "assignment_ids", columnDefinition = "jsonb")
    private List<UUID> assignmentIds;

    /** Average of the per-allocation optimizer scores for this plan. */
    @Column(name = "score", precision = 8, scale = 4)
    private BigDecimal score;

    @Column(name = "generated_by_user_id")
    private UUID generatedByUserId;

    @CreationTimestamp
    @Column(name = "generated_at", updatable = false)
    private Instant generatedAt;
}
