package com.recoverpro.server.enums;

public enum ReportType {
    AGENT_PERFORMANCE,
    TEAM_PERFORMANCE,
    AGENCY_PERFORMANCE,
    DAILY_VISIT_COMPLETION,
    MONTHLY_VISIT_COMPLETION,
    MONTHLY_LOAN_BOOK_SNAPSHOT,
    NPA_IDENTIFICATION,
    COLLECTION_EFFICIENCY,
    REASSIGNMENT_FREQUENCY,
    BANK_RECONCILIATION,
    MIS_EOD
}
