const list = await (await fetch('http://127.0.0.1:9222/json/list')).json();
const tgt = list[list.length - 1];
const ws = new WebSocket(tgt.webSocketDebuggerUrl);
let id = 0; const pend = new Map();
ws.onmessage = e => { const m = JSON.parse(e.data); if (m.id && pend.has(m.id)) { pend.get(m.id)(m); pend.delete(m.id); } };
await new Promise(r => ws.onopen = r);
const send = (method, params = {}) => new Promise(r => { const i = ++id; pend.set(i, r); ws.send(JSON.stringify({ id: i, method, params })); });
const evalJS = async expr => { const r = await send('Runtime.evaluate', { expression: expr, returnByValue: true, awaitPromise: true }); return r.result?.result?.value; };
const fs = await import('fs');

await send('Page.enable');
await send('Runtime.enable');
await send('Emulation.setDeviceMetricsOverride', { width: 1440, height: 1000, deviceScaleFactor: 1, mobile: false });
await send('Page.navigate', { url: 'http://localhost:3000/' });
await new Promise(r => setTimeout(r, 1800));
await evalJS(`document.querySelector('.rp-footer')?.scrollIntoView()`);
await new Promise(r => setTimeout(r, 500));
const shot = await send('Page.captureScreenshot', { format: 'png' });
fs.writeFileSync('C:/WINDOWS/TEMP/claude/F--F-Final/4e3d70e0-2376-456f-b5c3-555af5d9b5cc/scratchpad/pub-footer.png', Buffer.from(shot.result.data, 'base64'));
ws.close();
